# Generated by Django 3.2.16 on 2022-12-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gosto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GostosDoPsico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_psico', models.CharField(max_length=255)),
                ('gostos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esqueleto.gostos')),
            ],
        ),
        migrations.CreateModel(
            name='GostosDoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_paciente', models.CharField(max_length=255)),
                ('gostos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esqueleto.gostos')),
            ],
        ),
    ]
